- hosts: localhost
  tasks:
     - include_vars: "/root/cloud/var.yml"
     - package:
           name: nfs
           state: present
       ignore_errors: yes
     - service:
           name: nfs
           state: started
     - lineinfile:
           path: "/etc/exports"
           line: "/mnt/{{na}} *(rw,no_root_squash)"
     - service:
           name: nfs
           state: restarted
           enabled: yes
